### ISSUE TITLE
2024 Roadmap / Webi "v2"

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-roadmap#26]
Webi has become far too complex.

I wanted something with near-0 magic - which is why I opted for shell scripts.

But as I've added one case, and then another, and then another (and pivoted from the helper script to the `webi` command), it's bloated way too far.

There is a lot of necessary complexity, but there's also a lot of leftovers from the learning process.

My thoughts on fixing that:

- [x] `webi` needs to be its own command, not embedded in the bootstrap \
      (less scary, easier to lint, more fun to add `--whatever` too)
- [ ] `webi` should be offline-first \
      (ex: switch versions, reinstall most recent version)
- [ ] and yet... everything that can be decided ahead of time (online), should be
  - `webi_download` should be templated based on `curl` and `wget`
  - `webi_extract` should be templated based on `tar`, `xz`, `git` etc
  - add new APIs to support newer `webi` command
- [x] rename `bootstrap.sh` to `curl-pipe-bootstrap.sh` for clarity
- [x] rename `template.sh` to `install.tpl.sh` for clarity
- [ ] link to generate script from website (since the one in the repo may be more abstract)

This shouldn't really be Webi v2.0.0 - because it should be a smooth refactor with additional API on the server-side, not breaking changes, nor a from-scratch rewrite, nor a philosophical shift from the original goal.

Thoughts
- Git UA? https://stackoverflow.com/questions/29117355/git-clone-how-to-fake-user-agent
