### ISSUE TITLE
2023 Roadmap

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-roadmap#6]
## Sustain

- [ ] users + paid commercial use
- [ ] let users save custom bundle scripts `https://webi.ms/@dude/my-vpses` (or `https://dude.webi.ms/my-vpses`?)

## Simplify

- [x] eliminate `pathman`
   - [x] for Windows https://github.com/webinstall/webi-installers/issues/505
   - [x] for Unix https://github.com/webinstall/webi-installers/pulls/612
- [ ] eliminate the need for a bootstrap script 
  - (include pathman and zip/tar detect function in the installer itself?)

## Streamline

- [ ] create installers based on heuristics (per version?)
- [x] don't exclude BSD
- [x] add all domains to the HSTS preload list
  - [x] webinstall.dev: https://hstspreload.org/?domain=webinstall.dev
  - [x] webi.sh: https://hstspreload.org/?domain=webi.sh
  - [x] webi.ms: https://hstspreload.org/?domain=webi.ms
